### ISSUE TITLE
Unnecessary padding

### ISSUE THREAD

**Issue by nichtsen** [andreburgaud/crypt2go#5]
I recently import the repo in my [work](https://github.com/nichtsen/fcypt), however, some padding problems occurs:

`padLen := p.blockSize - (bufLen % p.blockSize)`
this operation set the padding length even if (bufLen % p.blockSize == 0), in which case the buffer is divided exactly
hence no more necessary to pad.
The current codes would catenate an extra and redandunt BLOCKSIZE bytes to the tail of block.

More details refere to [NIST Special Publication 800-38A](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf)  and PULL REQUEST

**Comment by andreburgaud** [comment]
@nichtsen After reading again the NIST document, I believe that the initial implementation was correct (barring any bugs). Padding is usually required, even if this means adding a full block unless you provide the length of the plain text along with a length indicator. The main point is to avoid any ambiguity when dealing with the plaintext and there should be a guarantee that the padding always exists even if the plain text had an exact multiple size block (or that you know the length of the message). 

In **Appendix A: Padding** of the NIST document https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf, it states the following:

> For the above padding method, the padding bits can be removed unambiguously, provided the
> receiver can determine that the message is indeed padded. **One way to ensure that the receiver
> does not mistakenly remove bits from an unpadded message is to require the sender to pad every
> message, including messages in which the final block (segment) is already complete**. For such
> messages, an entire block (segment) of padding is appended. Alternatively, such messages can
> be sent without padding if, for every message, the existence of padding can be reliably inferred,
> e.g., from a message length indicator. 

Here is the way to think about it. Imagine that you have a plain text with the last byte as `01`. If you know unambiguously that this was padded then you can safely "unpad" it. But, if the sender did not pad it because the plain text was of an exact multiple block size, then if you remove what you suspected to be padding, the message will be incorrect. 

The other approach, as stated in the last sentence, would be to send the length of the plaintext along with the message. I may consider adding a function that will take into account this notion and will not add an extra block.

I will publish an update that will take everything into account (full block padding and, like you suggested, no padding when the plaintext is of exact multiple block size.  I will also have to fix a few bugs that were reported and test that thoroughly. 

Thanks again for your contribution :-)

**Comment by andreburgaud** [comment]
I added a new section in the README and provided the resources explaining why there can be a full block of padding. This is mostly an extension of my previous comment above.

Thanks again for your help and the pertinence of your suggestion!
